name: "g2g_redtrans_dev_overfit_b512"

data:
    src: "de"                       # src language: expected suffix of train files, e.g. "train.de"
    trg: "gloss"                       # trg language
    train: "../dataset/Phoenix2014T_Extracted/phoenix2014T.train"    # training data
    dev: "../dataset/Phoenix2014T_Extracted/phoenix2014T.dev"      # development data for validation
    test: "../dataset/Phoenix2014T_Extracted/phoenix2014T.test"      # development data for validation
    random_train_subset: -1         # select this many training examples randomly for training and discard the rest, -1: all
    random_dev_subset: -1
    level: "word"                   # segmentation level: either "word", "bpe" or "char"
    lowercase: True                 # lowercase the data, also for validation
    max_sent_length: 400             # filter out longer sentences from training (src+trg)
    #src_vocab: "../dataset/Phoenx2014T_data/phoenix2014T.vocab.de"   # if specified, load a vocabulary from this file
    #trg_vocab: "../dataset/Phoenx2014T_data/phoenix2014T.vocab.gloss"  # one token per line, line number is index


testing:
    beam_size: 5
    alpha: 1.0

training:
    #load_model: "models/small_model/60.ckpt" # if given, load a pre-trained model from this checkpoint
    #reset_best_ckpt: False          # if True, reset the tracking of the best checkpoint and scores. Use for domain adaptation or fine-tuning with new metrics or dev data.
    #reset_scheduler: False          # if True, overwrite scheduler in loaded checkpoint with parameters specified in this config. Use for domain adaptation or fine-tuning.
    #reset_optimizer: False          # if True, overwrite optimizer in loaded checkpoint with parameters specified in this config. Use for domain adaptation or fine-tuning.
    random_seed: 42
    optimizer: "adam"
    normalization: "batch"
    adam_betas: [0.9, 0.999]
    learning_rate: .0001
#    learning_rate_min: 1.0e-07
#    scheduling: plateau
#    weight_decay: 0.001
#    patience: 8
#    decrease_factor: 0.7
    label_smoothing: 0.0
    loss: "crossentropy"
    epochs: 5000
    batch_size: 1
    batch_type: "sentence"
    batch_multiplier: 1
    early_stopping_metric: "eval_metric"
    validation_freq: 5
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "models_v2/test_g2g_train_b512_emd64_ff64_noscd_lr0.0001_EXD"
    overwrite: True
    shuffle: True
    use_cuda: False
    print_valid_sents: [0, 1, 2]
    keep_last_ckpts: 3

model:
    initializer: xavier
    bias_initializer: zeros
    init_gain: 1.0
    embed_initializer: xavier
    embed_init_gain: 1.0
    tied_softmax: false
    encoder:
        type: transformer
        num_layers: 1
        num_heads: 8
        embeddings:
            embedding_dim: 64
            scale: false
            dropout: 0.1
            norm_type: batch
            activation_type: softsign
        hidden_size: 64
        ff_size: 64
        dropout: 0.1
    decoder:
        type: transformer
        num_layers: 1
        num_heads: 8
        embeddings:
            embedding_dim: 64
            scale: false
            dropout: 0.1
            norm_type: batch
            activation_type: softsign
        hidden_size: 64
        ff_size: 64
        dropout: 0.1