name: "g2g_luong"

data:
    src: "de"                       # src language: expected suffix of train files, e.g. "train.de"
    trg: "gloss"                       # trg language
    train: "../dataset/Phoenx2014T_data/phoenix2014T_overfit.dev"    # training data
    dev: "../dataset/Phoenx2014T_data/phoenix2014T_overfit.dev"        # development data for validation
    test: "../dataset/Phoenx2014T_data/phoenix2014T_overfit.dev"        # test data for testing final model; optional
    random_train_subset: -1         # select this many training examples randomly for training and discard the rest, -1: all
    level: "word"                   # segmentation level: either "word", "bpe" or "char"
    lowercase: True                 # lowercase the data, also for validation
    max_sent_length: 30             # filter out longer sentences from training (src+trg)
    src_voc_min_freq: 1             # src minimum frequency for a token to become part of the vocabulary
    src_voc_limit: 101              # src vocabulary only includes this many most frequent tokens, default: unlimited
    trg_voc_min_freq: 1             # trg minimum frequency for a token to become part of the vocabulary
    trg_voc_limit: 102              # trg vocabulary only includes this many most frequent tokens, default: unlimited
    src_vocab: "../dataset/Phoenx2014T_data/phoenix2014T.vocab.de"   # if specified, load a vocabulary from this file
    trg_vocab: "../dataset/Phoenx2014T_data/phoenix2014T.vocab.gloss"  # one token per line, line number is index

testing:
    beam_size: 10
    alpha: 1.0

training:
    #load_model: "iwslt_envi_luong/XXXXX.cpkt"
    random_seed: 42
    optimizer: "sgd"
    learning_rate: 0.005
    learning_rate_min: 0.000000625
    weight_decay: 0.0
    clip_grad_norm: 5.0
    batch_size: 128
    scheduling: "plateau"
    patience: 1
    decrease_factor: 0.5
    early_stopping_metric: "eval_metric"
    epochs: 1000
    validation_freq: 10
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "models/g2g_luong"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 150
    print_valid_sents: [0, 1, 2]
    keep_last_ckpts: 3

model:
    initializer: "uniform"
    init_weight: 0.1
    embed_initializer: "uniform"
    embed_init_weight: 0.1
    bias_initializer: "uniform"
    bias_init_weight: 0.1
    init_rnn_orthogonal: False
    lstm_forget_gate: 0.
    encoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 512
            scale: False
        hidden_size: 512
        bidirectional: True
        dropout: 0.2
        num_layers: 1
    decoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 512
            scale: False
        emb_scale: False
        hidden_size: 512
        dropout: 0.2
        hidden_dropout: 0.2
        num_layers: 2
        input_feeding: True
        init_hidden: "zero"
        attention: "luong"
